name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".changeset/**.md"

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      id-token: write
      issues: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run changeset
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          commit: 'chore(packages): version packages'
          title: 'chore(packages): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.MY }}